- name: Flutter pub get
  working-directory: ./worldlive
  run: flutter pub get

- name: Build APK
  working-directory: ./worldlive
  run: flutter build apk --release

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: WorldLive-APK
    path: worldlive/build/app/outputs/flutter-apk/app-release.apk
